name: Autograding Tests
on:
  push:
  repository_dispatch:
  workflow_dispatch:    

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Configurar GitHub CLI con GITHUB_TOKEN   
      run: |
        echo $GITHUB_TOKEN | gh auth login --with-token
        
    - name: Verificar autenticación
      run: gh auth status
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autograde Reusable Workflows
      id: autograde-reusable-workflows
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograde Reusable Workflows
        setup-command: "sh .github/classroom/setup.sh"
        command: "sh .github/classroom/run-tests.sh"
        timeout: 60
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADE-REUSABLE-WORKFLOWS_RESULTS: "${{steps.autograde-reusable-workflows.outputs.result}}"
      with:
        runners: autograde-reusable-workflows
